@startuml
    Prasunamba -> Atlas_Batch1: Congratulations all
    Atlas_Batch1 --> Prasunamba: Thank you Meher

     Prasunamba -> Atlas_Batch1: Good luck for your Module 3
    Atlas_Batch1 --> Prasunamba: Thank you Meher in advance

    Prasunamba <-- Atlas_Batch1: Thank you Meher in advance    
@enduml
